import 'models/feed.dart';

class NewFeedData {
  List<FeedModel> newfeeddata = [
    FeedModel(
      fname: 'jaz_k',
      city: 'Hawassa',
      country: 'Ethiopia',
      profileImageurl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq7dDqaApR0N2jhw8SQglWnx41KEY1P1D1cg&usqp=CAU',
      bodyImageurl: [
        'https://media.gettyimages.com/id/691910455/photo/smiling-businessman-with-brown-bag-walking-in-city.jpg?s=612x612&w=gi&k=20&c=SdwY4B0sF3RMCo7x6C4BluYhwtN4T4AM8iIQzMi1e_Y=',
        'https://media.gettyimages.com/id/1171813390/photo/city-guy.jpg?s=612x612&w=0&k=20&c=PIEVG2KkrDVFYcDKkgPfU15rAUSJHK2_Al3j__E2Mx8=',
        'https://media.gettyimages.com/id/1179420343/photo/smiling-man-outdoors-in-the-city.jpg?s=612x612&w=0&k=20&c=8l-gOboGEFSyCFXr09EguDmV0E0bFT5usAms1wyFBh8='
      ],
      likes: [
        'yo_breezy',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'yo_breezy',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'jazz_k',
        'abe-be',
        'Alemu'
      ],
      comments: ['nicee', 'wowwww', 'cool', 'liked it'],
      discription:
          'the beauty of nature..the the beauty of nature the beauty of nature the beauty of nature the beauty of nature',
      postDate: DateTime.now(),
    ),
    FeedModel(
      fname: 'DanyKebede',
      city: 'Addis',
      country: 'Ethiopia',
      profileImageurl:
          'https://media.gettyimages.com/id/863488868/photo/portrait-of-smiling-young-man-in-city-on-sunny-day.jpg?s=612x612&w=gi&k=20&c=eriXzIiVWcRYGaA6O-9SBFJevNhNp-qpRoGgK3PBEjY=',
      bodyImageurl: [
        'https://media.gettyimages.com/id/1326660339/photo/using-phone-in-a-front-of-neon-lights-on-the-street.jpg?s=1024x1024&w=gi&k=20&c=munPm0L69kbCdRlBM6bxvIsyWthHUvZPpx-bdvOLO1M=',
        'https://media.gettyimages.com/id/1357555976/photo/a-young-couple-walking-in-the-city-at-night.jpg?s=1024x1024&w=gi&k=20&c=PiUvMyA3S__iKw9B4Sgen6fiAE5Nqp5W6i-D9G-1QQQ=',
        'https://media.gettyimages.com/id/691910449/photo/smiling-businessman-with-smart-phone-and-cup.jpg?s=612x612&w=0&k=20&c=xtKhWCfPYZrRjIs3cA_yFnxx3tx8CylnSt9knxib3qk=',
        'https://media.gettyimages.com/id/1171813390/photo/city-guy.jpg?s=612x612&w=0&k=20&c=PIEVG2KkrDVFYcDKkgPfU15rAUSJHK2_Al3j__E2Mx8=',
        'https://media.gettyimages.com/id/1179420343/photo/smiling-man-outdoors-in-the-city.jpg?s=612x612&w=0&k=20&c=8l-gOboGEFSyCFXr09EguDmV0E0bFT5usAms1wyFBh8='
      ],
      //
      likes: [
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu'
      ],
      comments: ['it\'s lit', 'wowwww', 'cool', 'nice'],
      discription: 'Enjoying the moment',
      postDate: DateTime.now(),
    ),
    FeedModel(
      fname: 'yopapa',
      city: 'BahirDar',
      country: 'Ethiopia',
      profileImageurl:
          'https://media.gettyimages.com/id/1171813390/photo/city-guy.jpg?s=612x612&w=0&k=20&c=PIEVG2KkrDVFYcDKkgPfU15rAUSJHK2_Al3j__E2Mx8=',
      bodyImageurl: [
        // 'https://media.gettyimages.com/id/691910455/photo/smiling-businessman-with-brown-bag-walking-in-city.jpg?s=612x612&w=gi&k=20&c=SdwY4B0sF3RMCo7x6C4BluYhwtN4T4AM8iIQzMi1e_Y=',
        // 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq7dDqaApR0N2jhw8SQglWnx41KEY1P1D1cg&usqp=CAU',
        'https://media.gettyimages.com/id/1179420343/photo/smiling-man-outdoors-in-the-city.jpg?s=612x612&w=0&k=20&c=8l-gOboGEFSyCFXr09EguDmV0E0bFT5usAms1wyFBh8='
      ],
      likes: [
        'yo_breezy',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'yo_breezy',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'DanyKebede',
        'jazz_k',
        'abe-be',
        'Alemu',
        'jazz_k',
        'abe-be',
        'Alemu'
      ],
      comments: ['nicee', 'wowwww', 'cool', 'liked it'],
      discription:
          'the beauty of nature..the the beauty of nature the beauty of nature the beauty of nature the beauty of nature',
      postDate: DateTime.now(),
    ),
  ];
}
